linters:
  enable:
    - govet         # Встроенный линтер Go
    - gosimple      # Упрощает код
    - gocyclo       # Проверяет сложность кода
    - errcheck      # Проверяет обработку ошибок
    - staticcheck   # Современные статические анализы
    - ineffassign   # Находит неиспользуемые присваивания
    - typecheck     # Проверяет типы
    - testifylint
    - revive
  disable:
    - godot         # Линтер, проверяющий точки в конце комментариев
    - dupl          # Находит дублирующийся код (может быть шумным)